<?php
/**
* Impact: Partnership Cloud for Magento
*
* @package     Impact_Integration
* @copyright   Copyright (c) 2021 Impact. (https://impact.com)
*/
$account_id = $this->data_from_db['account_id']??'';
$auth_token = $this->data_from_db['auth_token']??'';
$program_id = $this->data_from_db['program_id']??'';
$event_type_id = $this->data_from_db['event_type_id']??'';
$universal_tracking_tag = $this->data_from_db['universal_tracking_tag']??'';

$account_id = $account_id ? '**********'.substr($account_id, -4):$account_id;
$auth_token = $auth_token ? '**********'.substr($auth_token, -4):$auth_token;

?>
<script>
require([
    'jquery',
    'prototype',
], function(jQuery){

    var collectSpan = jQuery('#collect_span');

    function showConfig() {
        collectSpan.find('.landing').hide();
        collectSpan.find('.settings_page').show();
    }

    jQuery('#lpbtnid').click(function () {
        showConfig ();
    });
});
</script>

<span class="collect-indicator" id="collect_span">
<div class="landing" style="display:block; padding-left:80px">
  <div style="magin-left:100px">
                <div>
                <img src="https://uploaddeimagens.com.br/images/004/171/990/original/Screen_Shot_2022-11-21_at_22.33.23.png?1669080845" style="margin-left:50px" width="210" height="90">
                </div>
                <div style="display: inline-block; !important">
                <h1> <strong> Launch your affiliate and <br>  influencer program in  <br> minutes </strong></h1>
                    For as little as <span style="color:red">$30/month</span> you can: 
                    <br> <br> 
                    <div style="padding-left:20px">
                        <ul>
                        <li> Integrate your Magento store hassle-free</li>
                        <li>Get matched with the right affiliate and influencers</li>
                        <li>Accurately track affiliate and influencer performance</li>
                        <li>Automate partner payments</li>
                        </ul>
                    </div>
                </div>
                <div style="display: inline-block; !important">
                    <img src="https://uploaddeimagens.com.br/images/004/171/988/original/Screen_Shot_2022-11-21_at_22.28.37.png?1669080546" style="margin-left:50px" width="268" height="260">
                </div>
                <div>
                    <a target="_blank" href="https://impact-referral-partnerships.sjv.io/vnAMAW">
                        <img src="https://uploaddeimagens.com.br/images/004/172/010/original/Screen_Shot_2022-11-21_at_22.57.42.png?1669082301" style="margin-left:50px" width="250" height="60">
                    </a>
                </div>
                <div>
                    <a target="_blank" href="https://impact.com/adobecommerce-plans/?utm_source=adobecommerce&utm_medium=tech_partnerships&utm_campaign=applisting_learnmore&utm_content=learn_more_pricing" style="margin-left:90px">Learn more about pricing</a>
                </div>
                <div>
                    <img src="https://uploaddeimagens.com.br/images/004/172/015/original/Screen_Shot_2022-11-21_at_23.03.47.png?1669082724" style="margin-left:20px" width="650" height="75">
                </div>
                <div>
                    <img src="https://uploaddeimagens.com.br/images/004/172/017/original/Screen_Shot_2022-11-21_at_23.11.18.png?1669083104" style="margin-left:10px" width="650" height="550">
                </div>
                <div>
                    <a target="_blank" href="https://impact-referral-partnerships.sjv.io/vnAMAW">
                        <img src="https://uploaddeimagens.com.br/images/004/172/031/original/Screen_Shot_2022-11-21_at_23.34.18.png?1669084473" width="670" height="180">
                    </a>
                </div>
                <div style="margin-left:140px">
                    <br>
                    Already have an impact.com account? 
                    <a href="#">Set up your integration</a>
                </div>
        </div>
        </fieldset>
        </div>
</span>