<?php if($this->isActive()): ?>

    <script type="text/javascript"> !function () {
            !function () {
                const e = function (e, n) {
                    n || (n = window.location.href), e = e.replace(/[\[\]]/g, "\\$&");
                    var c = new RegExp("[?&]" + e + "(=([^&#]*)|&|#|$)").exec(n);
                    return c ? c[2] ? decodeURIComponent(c[2].replace(/\+/g, " ")) : "" : null
                }("irclickid");
                e && function (e, n, c) {
                    const i = new Date;
                    i.setTime(i.getTime() + 24 * c * 60 * 60 * 1e3);
                    const o = "expires=" + i.toUTCString();
                    document.cookie = e + "=" + n + ";SameSite=None;" + o + ";path=/"
                }("irclickid", e, 30)
            }()
        }();
    </script>
    <script type="text/javascript"> !function () {
            ire("generateClickId", function (e) {
                !function (e, i, t) {
                    const n = new Date;
                    n.setTime(n.getTime() + 24 * t * 60 * 60 * 1e3);
                    const c = "expires=" + n.toUTCString();
                    document.cookie = e + "=" + i + ";SameSite=None;" + c + ";path=/;secure"
                }("irclickid", e, 30)
            })
        }(); </script>

<?php endif; ?>